basePath: /api
definitions:
  common.Code:
    enum:
    - 0
    - 1
    - 2
    - 3
    - 4
    type: integer
    x-enum-varnames:
    - CodeSuccess
    - CodeFailure
    - CodeIllegal
    - CodeUnauthorized
    - CodeInternal
  common.Response:
    properties:
      code:
        allOf:
        - $ref: '#/definitions/common.Code'
        example: 0
      message:
        example: success
        type: string
      payload:
        x-nullable: true
    required:
    - code
    - message
    type: object
  model.Example:
    properties:
      code:
        type: integer
      created_at:
        type: string
      hash:
        type: string
      id:
        type: integer
      number:
        type: integer
      text:
        type: string
      time:
        type: string
      varchar:
        type: string
    type: object
info:
  contact:
    email: radixholms@gmail.com
    name: red
  description: API Layout
  title: API Layout
  version: "1.0"
paths:
  /module/example/data:
    get:
      description: Get an example by id
      operationId: get-an-example
      parameters:
      - description: example id
        example: 10001
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                payload:
                  $ref: '#/definitions/model.Example'
              type: object
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/common.Response'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/common.Response'
      summary: Get an example
    put:
      consumes:
      - application/json
      description: Put an example
      operationId: put-an-example
      parameters:
      - description: data to be saved
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Example'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/common.Response'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/common.Response'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/common.Response'
      summary: Put an example
swagger: "2.0"
